Item {
  id: root

  // EDGE STRIP BAR BEGIN — generated by omarchy-edge-strip/install.py
  property var edgeStripBars: ({})
  FileView {
    id: edgeStripState
    path: Quickshell.env("XDG_RUNTIME_DIR") + "/omarchy-edge-strip/state.json"
    watchChanges: true
    onFileChanged: reload()
    onLoaded: {
      try { root.edgeStripBars = JSON.parse(text()).bars || ({}) }
      catch(e) { root.edgeStripBars = ({}) }
    }
    onLoadFailed: root.edgeStripBars = ({})
  }
  function edgeStripMargin(screen, side) {
    var info = screen ? root.edgeStripBars[screen.name] : null
    return !root.barHidden && !root.vertical && info && info.fullBar ? -(info[side] || 0) : 0
  }
  // EDGE STRIP BAR END
  component BarPanel: PanelWindow {
    id: barWindow
    exclusionMode: root.barHidden ? ExclusionMode.Ignore : ExclusionMode.Auto
    margins {
      left: root.barHidden && root.position === "left" ? -root.barSize : root.edgeStripMargin(barWindow.screen, "left") // EDGE STRIP MARGIN
      right: root.barHidden && root.position === "right" ? -root.barSize : root.edgeStripMargin(barWindow.screen, "right") // EDGE STRIP MARGIN
    }
  }
}
